### ISSUE TITLE
Some Suggestions From Miru Extension Dev

### ISSUE THREAD

**Issue by OshekharO** [Mancrop/mancrop-miru#1]
### Describe your suggested feature

Maybe you can merge Linux support from here https://github.com/appdevelpo/miru-app

And for ios support and android improvised ui you can take from https://github.com/Tokyonth/mobru-app

If you are able to do this much it will be one hell of a application for otakus 😁

And one major notable issue is memory leak so take that into consideration.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by mingerfan** [comment]
@OshekharO Thank you for your issue report. I tried cloning and building the https://github.com/Tokyonth/mobru-app repository, but compilation failed on my machine. After comparing it with the original repo, I noticed the main updates are UI changes and iOS support. Given that I don't own any Apple devices nor have iOS development experience, I likely won't be diving deep into this codebase or merging it.

Regarding the issues you mentioned, I'll prioritize fixing:

Memory leaks
- re-editor replacement (and it is implemented in recent commit  https://github.com/Mancrop/mancrop-miru/commit/3d07232c388c8ee892b6c2938e0b8b888e9b5d67)
- iOS support will be a lower priority for me at this time.

By the way, could you please provide steps to reproduce the memory leak? I haven't been able to replicate this issue yet.

**Comment by mingerfan** [comment]
A new commit fix build problem, so can you help me check that?

**Comment by OshekharO** [comment]
![Screenshot_2024-12-03-08-45-22-77_3d73e98b1ad3bd2575f7a56513d89a0c](https://github.com/user-attachments/assets/f137682a-abc2-43cb-9287-bc4540fdd1cd)

Package not installed appears to be invalid.

**Comment by mingerfan** [comment]
fix it, now you can install miru in android

**Comment by OshekharO** [comment]
![Screenshot_2024-12-03-20-46-15-42_724c77a6924735f59ad9bef5bae520c3](https://github.com/user-attachments/assets/6b894607-c710-433a-b96c-f808866fd2c0)

Maybe you should just place the download icon next to favorite icon in details. Instead of creating whole block like download.

**Comment by mingerfan** [comment]
Download function is under development now, so it is just an useless icon. The position of it will be carefully considered once download function is implemented.

**Comment by OshekharO** [comment]
> Download function is under development now, so it is just an useless icon. The position of it will be carefully considered once download function is implemented. As for slack problem, I have no idea on how to solve it. I don't really know if it is happened in (original) miru.

lagging in details while scrolling overview haven't noticed in original unless the extension is api based and that too if it have huge based.

**Comment by mingerfan** [comment]
Thank you for your suggestion. I have fixed the delay and UI issues in the latest commit (but unfortunately, due to performance concerns, the image blur feature has been removed)

**Comment by OshekharO** [comment]
> Thank you for your suggestion. I have fixed the delay and UI issues in the latest commit (but unfortunately, due to performance concerns, the image blur feature has been removed) ![1f5a3b4b00bfb5ed7468a3d9e2b7f526](https://private-user-images.githubusercontent.com/89310654/393604438-733111fd-45de-4f61-bd5e-a4ee97a144fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzAyNTQsIm5iZiI6MTczMzY2OTk1NCwicGF0aCI6Ii84OTMxMDY1NC8zOTM2MDQ0MzgtNzMzMTExZmQtNDVkZS00ZjYxLWJkNWUtYTRlZTk3YTE0NGZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE0NTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjYyNDA4ZmJiMzZmNWJjOTI2ZWFkNGM3MzM2MDQ2YzRlYWJiODYzOTcwMmQ5MDBmM2Q0NzY3MTYyYzk0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pBBHWqTzyY5POwUrfq5lYi0n_QpwsVa8gdEfN4OTN8I)

It doesn't really matter performance much more important then superficial features. Stability is important.

**Comment by OshekharO** [comment]
Also I think web view is broken it doesn't open the website.

**Comment by OshekharO** [comment]
![Screenshot_2024-12-08-20-33-23-22_724c77a6924735f59ad9bef5bae520c3](https://github.com/user-attachments/assets/e85caa2b-88d9-4507-ad8f-71c3cd201bf6)

Also I think web view is broken it doesn't open the website.

**Comment by mingerfan** [comment]
I tried it in original miru, webview is broken too. Will fix it after I complete download function

**Comment by OshekharO** [comment]
There is some issue with the download manager. For example when I selected only 1 chapter to download it downloads 3 chapter or more i.e. as per max task set in download settings.

And after I deleted the downloaded chapter it starts malfunctioning for example I selected 3 chapter to download after deleting it downloaded chapter 1, 2, 3, 4 and so on.

**Comment by OshekharO** [comment]
Also I think it is a good option if you can add inbuilt dns options. Also I think settings needs to be revamped.

**Comment by mingerfan** [comment]
> There is some issue with the download manager. For example when I selected only 1 chapter to download it downloads 3 chapter or more i.e. as per max task set in download settings.
> 
> And after I deleted the downloaded chapter it starts malfunctioning for example I selected 3 chapter to download after deleting it downloaded chapter 1, 2, 3, 4 and so on.

I've only implemented a demo framework for the download service and download manager so far. Hopefully, the development will be completed in a few days and released in version 1.9.0. I'll keep you updated when it's ready.

**Comment by OshekharO** [comment]
@mingerfan if you going to overhaul the whole ui then I suggest you this one to look into maybe catch your eye 😉 https://pub.dev/packages/neubrutalism_ui or just search neubrutalism for ui designs

**Comment by mingerfan** [comment]
Thanks. UI improvements are not a high-priority task, so I plan to work on them after implementing the basic functionality.

**Comment by OshekharO** [comment]
> Thanks. UI improvements are not a high-priority task, so I plan to work on them after implementing the basic functionality.

Yup, I agree that's why I said if 👍

**Comment by OshekharO** [comment]
How about adding Android TV Support?

**Comment by mingerfan** [comment]
Android TV support is not on my list right now since it requires a lot of work and few people would use Miru on TV. As for the reader UI improvement, you're right. I just need to balance my open-source development with my studies, so it might take some time:(

**Comment by mingerfan** [comment]
By the way, you can now download specific chapters of a manga on Windows and Android, so feel free to try it out. The download manager is actively being developed to allow users to stop and resume download tasks.

**Comment by OshekharO** [comment]
@mingerfan how about using tachiyomi based extension in this fork instead of default miru Extension? Development scope of tachiyomi extension is much larger and it has all contents like anime, movie, novel, manga and so on.

**Comment by mingerfan** [comment]
Yes, your mention of supporting Tachiyomi is indeed on my agenda. However, in reality, Tachiyomi has ceased development for certain reasons, so I plan to use a third-party plugin library maintained by Keiyoushi (https://keiyoushi.github.io/). Since Tachiyomi plugins are written in Kotlin, cross-platform support for these plugins is actually quite challenging, if not impossible. Stay tuned, as I will explore how to make it happen or prove that it's unfeasible :)

**Comment by mingerfan** [comment]
The first commit of the New Year! I've implemented manga downloading and offline reading (the default download path is under Documents). Welcome to test it out: https://github.com/Mancrop/mancrop-miru/actions/runs/12572441690. Currently, background downloads on the Android side require manual permission for notifications, so the implementation is still not very elegant. This will be improved in the future. Happy New Year!
![image](https://github.com/user-attachments/assets/5e9e0e50-10ef-49aa-8fe7-c12c9c611d07)
![image](https://github.com/user-attachments/assets/5f765aaa-908e-4d4a-b352-5bf4660833dd)

**Comment by OshekharO** [comment]
Happy New year 🎊

**Comment by mingerfan** [comment]
A preload technique is added in the newest commit, will greatly improve comic reading experiment. See this site https://github.com/Mancrop/mancrop-miru/issues/7#issuecomment-2571362448. Besides, non-production release is compatible with tag release now, that is, you can install miru and miru-dev simultaneously on your phone.

**Comment by mingerfan** [comment]
@OshekharO We're excited to announce the first stable release! The new version now supports manga and video downloads. Feel free to try it out - look forward to your feedback.

**Comment by OshekharO** [comment]
@mingerfan hii have tested the application and noticed few things like uninstall extension option is not full showing in extension manager and webview thing is still broken. And some sluginess in detail page.

**Comment by mingerfan** [comment]
I can't reproduce these problems(slaginess and uninstall options)，can you provide some screen shots or screen recordings to help me reproduce them?

![Image](https://github.com/user-attachments/assets/f8f32a11-a2d4-4cc4-92bc-d2f8b4d35f17)

**Comment by OshekharO** [comment]
> I can't reproduce these problems(slaginess and uninstall options)，can you provide some screen shots or screen recordings to help me reproduce them?
> 
> ![Image](https://github.com/user-attachments/assets/f8f32a11-a2d4-4cc4-92bc-d2f8b4d35f17)
> 
> Will fix webview problem soon.

Uninstall thing is occurring rarely. As for sluginess it's occuring in some extension when switching from chapters/video to description

**Comment by mingerfan** [comment]
Thanks. Lag and webview issues are in queue. See https://github.com/Mancrop/mancrop-miru/issues/11 and https://github.com/Mancrop/mancrop-miru/issues/12

**Comment by mingerfan** [comment]
WebView problem can not be fixed unless add a new plugin api. Please see https://github.com/Mancrop/mancrop-miru/issues/12#issuecomment-2668065967
